import Head from "next/head";
import { ReactElement } from "react";
import Footer from "./Footer";
import Header from "./Header";

type Props = {
  title: String;
  children: ReactElement | ReactElement[];
};

export default function Layout({ title, children }: Props): ReactElement {
  return (
    <>
      <Head>
        <title>MLES | {title && title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {children}
      <Footer />
    </>
  );
}
